version: '3'
services:
    postgres:
        image: postgres:alpine
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=teste
            - POSTGRES_USER=teste
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - ./postgres/:/var/lib/postgresql/data/pgdata
    pgadmin4:
        image: dpage/pgadmin4
        restart: always
        depends_on:
            - postgres
        ports:
            - 5050:80
        environment:
            - PGADMIN_DEFAULT_EMAIL=user@domain.com
            - PGADMIN_DEFAULT_PASSWORD=SuperSecret
    mongodb:
        build: .
        restart: always
        image: mongo:bionic
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=teste
            - MONGO_INITDB_ROOT_PASSWORD=teste
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8082:8080
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
    userservice:
        build: ../userService/
        restart: always
        ports:
            - 8080:8080
    accountservice:
        build: ../accountService
        restart: always
        ports:
            - 8081:8081
    web:
        build: ../web-app
        restart: always
        ports:
            - 3000:3000